version: '3.3'

services:
  kk_web:
    container_name: kk_web
    build: ./app/
    ports:
      - "8008:8008"
    command: sh -c "python manage.py runserver 0.0.0.0:8008"
    restart: always
    env_file:
      - ./app/.env
    volumes:
      - ./app/:/app/
