version: '3.3'

services:
  kk_web:
    container_name: kk_web
    build: ./app/
    ports:
      - "8008:8008"
    command: sh -c "python manage.py runserver 0.0.0.0:8008"
    restart: always
    env_file:
      - ./app/.env
    volumes:
      - ./app/:/app/

  kk_redis:
    container_name: kk_redis
    image: redis:alpine
  
  kk_celery:
    container_name: kk_celery
    build: ./app/
    command: celery -A core worker -l info
    volumes:
      - ./app/:/app/
    restart: always
    env_file:
      - ./app/.env
  
  kk_celery_beat:
    container_name: kk_celery_beat
    build: ./app/
    command: celery -A core beat -l info
    volumes:
      - ./app/:/app/
    restart: always
    env_file:
      - ./app/.env