# Generated by Django 4.1 on 2024-01-18 16:08

from django.db import migrations, models
import oauth.validators


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='passport'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[oauth.validators.validate_phone], verbose_name='phone'),
        ),
    ]
