# Generated by Django 4.1 on 2025-08-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_alter_historicaluser_surname_alter_user_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='type',
            field=models.CharField(choices=[('worker', 'worker'), ('candidate', 'candidate')], default='worker', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('worker', 'worker'), ('candidate', 'candidate')], default='worker', max_length=255),
        ),
    ]
