# Generated by Django 4.1 on 2025-10-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0008_historicaluser_type_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='birth place'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='passport date'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='birth place'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='passport date'),
        ),
    ]
