# Generated by Django 4.1 on 2025-07-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazard',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='med',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
