# Generated by Django 4.1 on 2025-07-02 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mprofid', '0002_alter_hazard_name_alter_med_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerInvoice',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ConclusionStatus',
        ),
        migrations.DeleteModel(
            name='Med',
        ),
        migrations.RemoveField(
            model_name='order',
            name='hazards',
        ),
        migrations.RemoveField(
            model_name='order',
            name='med_client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pay_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='order',
            name='services',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subdivision',
        ),
        migrations.RemoveField(
            model_name='order',
            name='survey_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='hazards',
        ),
        migrations.RemoveField(
            model_name='profession',
            name='med_client',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.RemoveField(
            model_name='subdivision',
            name='med_client',
        ),
        migrations.DeleteModel(
            name='Hazard',
        ),
        migrations.DeleteModel(
            name='MedClient',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Part',
        ),
        migrations.DeleteModel(
            name='PayType',
        ),
        migrations.DeleteModel(
            name='Profession',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Subdivision',
        ),
        migrations.DeleteModel(
            name='SurveyType',
        ),
    ]
