# Generated by Django 4.1 on 2025-08-14 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mprofid', '0003_workerinvoice_delete_conclusionstatus_delete_med_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerinvoice',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
