# Generated by Django 4.1 on 2024-09-09 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worker', '0002_historicalworkerdoc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctype',
            options={'verbose_name': 'Тип документа', 'verbose_name_plural': 'Тип документов'},
        ),
        migrations.AlterModelOptions(
            name='historicalworkerdoc',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Документа сотрудника', 'verbose_name_plural': 'historical Документы сотрудника'},
        ),
        migrations.AlterModelOptions(
            name='workerdoc',
            options={'verbose_name': 'Документа сотрудника', 'verbose_name_plural': 'Документы сотрудника'},
        ),
        migrations.AlterField(
            model_name='historicalworkerdoc',
            name='create_date',
            field=models.DateField(blank=True, editable=False, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='historicalworkerdoc',
            name='expired_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончание'),
        ),
        migrations.AlterField(
            model_name='historicalworkerdoc',
            name='file',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='historicalworkerdoc',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начало'),
        ),
        migrations.AlterField(
            model_name='historicalworkerdoc',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='worker.doctype', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='historicalworkerdoc',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользовател'),
        ),
        migrations.AlterField(
            model_name='workerdoc',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создание'),
        ),
        migrations.AlterField(
            model_name='workerdoc',
            name='expired_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончание'),
        ),
        migrations.AlterField(
            model_name='workerdoc',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='user-docs', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='workerdoc',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начало'),
        ),
        migrations.AlterField(
            model_name='workerdoc',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.doctype', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='workerdoc',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользовател'),
        ),
    ]
