# Generated by Django 4.1 on 2024-01-18 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertoorganization',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='usertoorganization',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='usertoorganization',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('client', 'Client'), ('worker', 'Worker')], default='worker', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='usertoorganization',
            name='status',
            field=models.CharField(choices=[('checking', 'Checking'), ('done', 'Done'), (None, 'Nothing')], max_length=20, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='usertoorganization',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользовател'),
        ),
    ]
