# Generated by Django 4.1 on 2024-01-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_address_alter_organization_bik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoorganization',
            name='status',
            field=models.CharField(choices=[('checking', 'Checking'), ('done', 'Done')], max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
