# Generated by Django 4.1 on 2024-01-22 12:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0005_organization_email_organization_gen_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='has_skud',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HistoricalOrganization',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('inn', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'Неправильный ИНН'), django.core.validators.MaxLengthValidator(10, 'Неправильный ИНН')], verbose_name='ИНН')),
                ('bik', models.CharField(blank=True, max_length=255, null=True, verbose_name='ВИК')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('ogrn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ОГРН')),
                ('kpp', models.CharField(blank=True, max_length=20, null=True, verbose_name='КПП')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gen_name', models.CharField(blank=True, max_length=255, null=True)),
                ('r_s', models.CharField(blank=True, max_length=255, null=True)),
                ('k_s', models.CharField(blank=True, max_length=255, null=True)),
                ('has_skud', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Организация',
                'verbose_name_plural': 'historical Организации',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
